# -*- coding: utf-8 -*-

# Copyright (c) 2013 Daniel Prokscha
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Single byte commands.
ON = '\x10'
OFF = '\x00'
ON_BRIGHTNESS_LEVEL_1 = '\x01'
ON_BRIGHTNESS_LEVEL_2 = '\x02'
ON_BRIGHTNESS_LEVEL_3 = '\x03'
ON_BRIGHTNESS_LEVEL_4 = '\x04'
ON_BRIGHTNESS_LEVEL_5 = '\x05'
ON_BRIGHTNESS_LEVEL_6 = '\x06'
ON_BRIGHTNESS_LEVEL_7 = '\x07'
ON_BRIGHTNESS_LEVEL_8 = '\x08'
ON_BRIGHTNESS_LEVEL_9 = '\x09'
ON_BRIGHTNESS_LEVEL_10 = '\x0a'
ON_BRIGHTNESS_LEVEL_11 = '\x0b'
ON_BRIGHTNESS_LEVEL_12 = '\x0c'
ON_BRIGHTNESS_LEVEL_13 = '\x0d'
ON_BRIGHTNESS_LEVEL_14 = '\x0e'
ON_BRIGHTNESS_LEVEL_15 = '\x0f'
ON_BRIGHTNESS_LEVEL_16 = '\x10'
ON_LAST_BRIGHTNESS_LEVEL = '\x11'
TOGGLE = '\x12'
DIM_UP = '\x13'
DIM_DOWN = '\x14'
DIM_UP_AND_DOWN = '\x15'
CHANGE_INTERNAL_TIMER = '\x16'
EDUCATE = '\x17'
OFF_INTERNAL_TIME_THEN_LAST_BRIGHTNESS_LEVEL = '\x18'
ON_INTERNAL_TIME = '\x19'
ON_LAST_BRIGHTNESS_LEVEL_INTERNAL_TIME_THEN_OFF = '\x1a'
RESET = '\x1b'
ON_INTERNAL_TIMER_THEN_PREVIOUS_STATE = '\x1e'
ON_LAST_BRIGHTNESS_LEVEL_INTERNAL_TIME_THEN_PREVIOUS_STATE = '\x1f'

# Commands with additional byte.
DIM_IN_TIME_OFF = '\x20'
DIM_IN_TIME_BRIGHTNESS_LEVEL_1 = '\x21'
DIM_IN_TIME_BRIGHTNESS_LEVEL_2 = '\x22'
DIM_IN_TIME_BRIGHTNESS_LEVEL_3 = '\x23'
DIM_IN_TIME_BRIGHTNESS_LEVEL_4 = '\x24'
DIM_IN_TIME_BRIGHTNESS_LEVEL_5 = '\x25'
DIM_IN_TIME_BRIGHTNESS_LEVEL_6 = '\x26'
DIM_IN_TIME_BRIGHTNESS_LEVEL_7 = '\x27'
DIM_IN_TIME_BRIGHTNESS_LEVEL_8 = '\x28'
DIM_IN_TIME_BRIGHTNESS_LEVEL_9 = '\x29'
DIM_IN_TIME_BRIGHTNESS_LEVEL_10 = '\x2a'
DIM_IN_TIME_BRIGHTNESS_LEVEL_11 = '\x2b'
DIM_IN_TIME_BRIGHTNESS_LEVEL_12 = '\x2c'
DIM_IN_TIME_BRIGHTNESS_LEVEL_13 = '\x2d'
DIM_IN_TIME_BRIGHTNESS_LEVEL_14 = '\x2e'
DIM_IN_TIME_BRIGHTNESS_LEVEL_15 = '\x2f'
DIM_IN_TIME_BRIGHTNESS_LEVEL_16 = '\x30'
DIM_IN_TIME_LAST_BRIGHTNESS_LEVEL = '\x31'
DIM_IN_TIME_UP_AND_DOWN = '\x32'
DIM_UP_THEN_OFF_IN_TIME = '\x33'
DIM_DOWN_THEN_OFF_IN_TIME = '\x34'
DIM_THEN_OFF_IN_TIME = '\x35'
SET_INTERNAL_TIMER = '\x36'
OFF_FOR_TIME_THEN_LAST_BRIGHTNESS_LEVEL = '\x38'
ON_FOR_TIME_THEN_OFF = '\x39'
ON_FOR_TIME_LAST_BRIGHTNESS_LEVEL_THEN_OFF = '\x3a'
SET_INTERNAL_TIMER_DIM_UP = '\x3c'
SET_INTERNAL_TIMER_DIM_DOWN = '\x3d'
ON_FOR_TIME_THEN_PREVIOUS_STATE = '\x3e'
ON_FOR_TIME_LAST_BRIGHTNESS_LEVEL_THEN_PREVIOUS_STATE = '\x3f'